/* User-facing strings.
 *
 * Components never hold string literals (AGENTS.md). This module is the single
 * lookup they go through, shaped like the Fluent API it will become: ids are
 * stable and English-ish but not derived from the copy, so rewording a string
 * does not orphan its translations.
 *
 * Deliberately not @fluent/react yet — with one locale that would be ceremony.
 * What matters now is that the *call sites* are right, because those are what is
 * expensive to retrofit; swapping this file's backing store for a real .ftl
 * bundle touches this file only. See docs 07 §13.
 */

type Args = Record<string, string | number>;

const en = {
  'app-name': 'Petrel',

  'rail-mailboxes': 'Mailboxes',
  'rail-switch-account': 'Switch account',
  'mailbox-inbox': 'Inbox',
  'mailbox-starred': 'Starred',
  'mailbox-snoozed': 'Snoozed',
  'mailbox-sent': 'Sent',
  'mailbox-drafts': 'Drafts',
  'mailbox-outbox': 'Outbox',
  'mailbox-archive': 'Archive',
  'mailbox-spam': 'Spam',
  'mailbox-trash': 'Trash',

  'search-placeholder': 'Search this account…',
  'list-conversations': '{ $count } conversations',
  'list-unread': '{ $count } unread',

  'reader-archive': 'Archive',
  'reader-star': 'Star',
  'reader-more': 'More actions',
  'menu-star': 'Star',
  'menu-unstar': 'Remove star',
  'menu-spam': 'Report as spam',
  'reader-mark-read': 'Mark as read',
  'reader-mark-unread': 'Mark as unread',
  'qact-archive': 'Archive',
  'qact-mark-read': 'Mark as read',
  'qact-mark-unread': 'Mark as unread',
  'qact-snooze': 'Snooze',
  'reader-message-count': '{ $count } messages',
  'list-inbox-heading': 'Inbox',
  'search-hint-key': '/',
  'rail-tags': 'Tags',
  'rail-collapse': 'Collapse sidebar',
  'rail-expand': 'Expand sidebar',
  'rail-resize': 'Resize sidebar',
  'rail-help': 'Help & Shortcuts',
  'rail-settings': 'Settings',
  'titlebar-sync': 'all mail synced',
  'reader-snooze': 'Snooze',
  'reader-reply': 'Reply',
  'reader-reply-all': 'Reply all',
  'reader-forward': 'Forward',
  'reader-failed': 'Could not open this conversation',
  'reader-to': 'to { $who }',
  'reader-collapse': 'Collapse message from { $who }',
  'reader-earlier': '{ $count } earlier messages',
  'reader-none-title': 'Nothing selected',
  'reader-none-body': 'Pick a conversation with J and K, or press Enter to open one.',

  'empty-inbox-title': 'Inbox is clear',
  'empty-view-title': 'Nothing in { $view }',
  'empty-view-body': 'Conversations you move here will show up in this list.',
  'empty-notbuilt-title': '{ $view } is not built yet',
  'empty-notbuilt-body': 'The view is here so the shape of the app is honest; nothing fills it until the feature lands.',
  'empty-snoozed-body': 'Put a conversation aside with { $key } and it waits here until it is due.',
  'empty-starred-body': 'Star a conversation with { $key } and it will be here.',
  'empty-sent-body': 'Petrel cannot send mail yet, so nothing has landed here.',
  'empty-drafts-body': 'Composing is not built yet, so there are no drafts to keep.',
  'empty-inbox-body': 'Nothing left to triage. Snoozed mail comes back when you asked it to.',
  'empty-search-title': 'No matches for “{ $query }”',
  'empty-search-body': 'All { $count } messages were searched.',
  'empty-loading': 'Loading your mail…',
  'empty-syncing': 'Fetching your mail — { $count } so far…',

  'sync-failed-title': 'Could not reach your mail',
  'sync-failed-body': 'Showing what Petrel already had — nothing is lost. Details in sync.log.',
  'compose-title': 'Compose',
  'compose-new': 'New message',
  'compose-reply': 'Reply',
  'compose-from': 'From',
  'compose-to': 'To',
  'compose-cc': 'Cc',
  'compose-subject': 'Subject',
  'compose-body': 'Message',
  'compose-send': 'Send',
  'compose-attach': 'Attach',
  'compose-no-recipient': 'Add someone to send to.',
  'compose-sending': 'Sending in { $count }s',
  'compose-send-now': 'Send now',
  'compose-sent': 'Sent',
  'compose-cancelled': 'Held — nothing was sent',
  'compose-failed': 'Not sent — { $error }',
  'notify-paused-toast': 'Notifications paused for an hour',
  'notify-pause': 'Pause notifications',
  'notify-pause-help': 'Nothing will interrupt you while paused. Mail still arrives.',
  'notify-paused-until': 'Paused until { $when }.',
  'notify-pause-off': 'Off',
  'notify-pause-hour': 'For an hour',
  'notify-pause-tomorrow': 'Until tomorrow',
  'notify-level': 'What earns an interruption',
  'notify-level-help': 'Priority means starred conversations for now; this grows as Petrel learns what you act on.',
  'notify-level-all': 'All new mail',
  'notify-level-priority': 'Priority only',
  'notify-level-none': 'Nothing',
  'notify-desktop': 'Desktop notifications',
  'notify-desktop-help': 'Notifications outside the window go through macOS, which can refuse them. The in-app message always appears.',
  'notify-desktop-on': 'On',
  'notify-desktop-off': 'Off',
  'notify-test': 'Send a test notification',
  'notify-test-body': 'Notifications are working.',
  'notify-one': 'New message from { $who }',
  'notify-many': '{ $count } new messages',
  'status-synced': 'Synced just now',
  'status-seeding': 'Building your mailbox…',
  'status-counts': '{ $count } conversations · { $unread } unread',

  'cmd-archive': 'Mark Done',
  'cmd-archive-alias': 'Archive',
  'cmd-snooze': 'Snooze this conversation',
  'cmd-star': 'Star',
  'cmd-tag': 'Tag',
  'cmd-move': 'Move to folder',
  'cmd-reply': 'Reply',
  'cmd-trash': 'Move to trash',
  'cmd-compose': 'Compose',
  'cmd-search': 'Search',
  'cmd-pause-notifications': 'Pause notifications for 1 hour',
  'hint-folder': 'folder',
  'hint-settings': 'settings',
  'settings-title': 'Settings',
  'settings-accounts': 'Accounts',
  'settings-identities': 'Identities & Signatures',
  'settings-composing': 'Composing',
  'settings-notifications': 'Notifications',
  'settings-appearance': 'Appearance',
  'settings-privacy': 'Privacy & Security',
  'settings-storage': 'Storage & Data',
  'settings-not-built': 'This pane is not built yet.',
  'accounts-yours': 'Your accounts',
  'accounts-add': 'Add account',
  'accounts-none': 'No accounts yet.',
  'accounts-failed': 'Could not read your accounts',
  'accounts-synced': 'synced { $when }',
  'accounts-storage': '{ $count } messages stored on this Mac.',
  'accounts-colour': 'Colour',
  'accounts-colour-help': 'Marks this account across the app.',
  'accounts-keep': 'When mail disappears from the server',
  'accounts-keep-mirror': 'Gone there, gone here — after a 30-day grace period in case it was a mistake.',
  'accounts-keep-archive': 'Petrel keeps its copy after the server drops it. Your archive outlives the mailbox — and grows without limit.',
  'accounts-mirror': 'Mirror the server',
  'accounts-archive': 'Keep a local archive',
  'accounts-folders': 'Where things go',
  'accounts-folders-help': 'Every provider names its folders differently — Sent, Sent Items, [Gmail]/Sent Mail. Petrel asks the server which folder is which, so archiving and deleting land where you would expect. Change one only if your provider has labelled something oddly.',
  'accounts-folders-none': 'Not known yet — Petrel asks the server for this the first time an account syncs, and this one has not.',
  'folder-archive': 'Archive',
  'folder-sent': 'Sent',
  'folder-drafts': 'Drafts',
  'folder-spam': 'Spam',
  'folder-trash': 'Trash',
  'folder-unmapped': 'not mapped',
  'appearance-theme': 'Theme',
  'appearance-theme-help': 'System follows your operating system, including on a schedule.',
  'theme-light': 'Light',
  'theme-dark': 'Dark',
  'theme-system': 'System',
  'appearance-language': 'Language',
  'appearance-language-help': "System follows your Mac's language. Petrel falls back to English for anything not yet translated.",
  'language-system': 'System — English',
  'appearance-accent': 'Accent',
  'appearance-accent-help': 'Used for selection, unread marks and the one emphasised action on any screen.',
  'appearance-list': 'Message list',
  'appearance-list-help': 'Density affects the list only — the message you are reading keeps its comfortable size.',
  'appearance-density': 'Density',
  'appearance-reading-pane': 'Reading pane',
  'density-relaxed': 'Relaxed',
  'density-compact': 'Compact',
  'layout-right': 'Right',
  'layout-below': 'Below',
  'layout-off': 'Off',
  'appearance-text-size': 'Reading text size',
  'appearance-text-size-help': 'Message bodies only. Interface text follows your system settings.',
  'reset': 'Reset',
  'help-title': 'Help',
  'help-tab-shortcuts': 'Shortcuts',
  'help-tab-search': 'Search',
  'help-filter-shortcuts': '…filter shortcuts',
  'help-filter-search': '…filter search filters',
  'help-together': 'Putting it together',
  'help-together-note': 'From Sam, since June, with a file attached, mentioning the annex. The filter buttons type this for you.',
  'close': 'Close',
  'close-title': 'Close (Esc)',
  'picker-folder-title': 'Move to folder',
  'picker-tag-title': 'Tag',
  'picker-folder-hint': '…type to filter',
  'picker-tag-hint': 'Type to filter or create',
  'picker-new-folder': 'New folder “{ $name }”…',
  'picker-new-tag': 'New tag “{ $name }”…',
  'picker-snooze-title': 'Snooze',
  'picker-snooze-hint': 'Bring this back…',
  'picker-snooze-foot': 'Snooze is Petrel\u2019s, not the server\u2019s: the conversation stays in your inbox everywhere else until it comes back here.',
  'snooze-later': 'Later today',
  'snooze-tomorrow': 'Tomorrow',
  'snooze-weekend': 'This weekend',
  'snooze-next-week': 'Next week',
  'picker-none': 'Nothing matches.',
  'picker-folder-foot':
    'On Gmail this changes labels rather than moving anything, which is what Gmail means by a folder. The result matches what you would see in the web client.',
  'picker-tag-foot': 'Tags stay on the conversation wherever it is filed.',
  'palette-placeholder': 'Type a command…',
  'palette-group-conversation': 'This conversation',
  'palette-group-goto': 'Go to',
  'palette-group-app': 'Petrel',
  'palette-empty': 'Nothing matches “{ $query }”',
  'palette-navigate': 'navigate',
  'palette-run': 'run',
  'palette-all-shortcuts': 'all shortcuts',
  'palette-more': '{ $count } more results',
  'not-implemented': '{ $label } is not built yet',
  'triage-failed': 'Could not do that — { $error }',
  'undo-done': 'Undone',
  'undo-too-late': 'Too late to undo — that already went to the server',
  'undo': 'Undo',
  'account-switched': 'Switched to { $email }',
  'account-none-at': 'No account at { $n }',

  'a11y-message-list': 'Conversations',
  'a11y-row': '{ $unread }{ $from }, { $subject }, { $time }',
  'a11y-unread-prefix': 'unread, ',
} as const;

export type StringId = keyof typeof en;

/** Fluent-style interpolation: `{ $name }` holes, filled positionally by key. */
export function t(id: StringId, args?: Args): string {
  const raw: string = en[id];
  if (!args) return raw;
  return raw.replace(/\{\s*\$(\w+)\s*\}/g, (whole, key: string) =>
    key in args ? String(args[key]) : whole,
  );
}
